services:
  postgres:
    image: postgres:17
    container_name: shiplist-local-db
    hostname: ${DB_HOST}

    ports:
      - "5432:${DB_PORT}"

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: